[package]
name = "raitha_darpana"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
image = "0.25"
anyhow = "1"
base64 = "0.22.1"
log = "0.4"
env_logger = "0.11"
headless_chrome = "1.0.22"
scraper = "0.27.0"
clap = { version = "4.6.4", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
ratatui = "0.29"
ratatui-image = "9.0.0"
crossterm = "0.28"